# Generated by Django 5.2.5 on 2025-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Содержимое")),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="blog/photo", verbose_name="Изображение"),
                ),
                ("is_published", models.BooleanField(verbose_name="Признак публикации")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("views_count", models.PositiveIntegerField(default=0, verbose_name="Счетчик просмотров")),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
                "ordering": ["title"],
            },
        ),
    ]
