# Generated by Django 5.2.5 on 2025-09-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contactinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="catalog/photo", verbose_name="Изображение"),
        ),
    ]
